server:
 port: 9191
 
spring:
 application:
  name: API-GATEWAY
 cloud:
  gateway:
   routes:
    - id: USER-SERVICE
      uri: lb://USER-SERVICE
      predicates:
        - Path=/users/** 
      filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback/userFallback  
    - id: DEPARTMENT-SERVICE
      uri: lb://DEPARTMENT-SERVICE
      predicates:
        - Path=/departments/**  
      filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback/departmentFallback  
  
#eurka client settings
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:8761/eureka/
 instance:
  hostname: localhost 